---
title: "Visualizing the Crime Incidents in Buffalo, NY"
author: Wei Liu
output: 
  github_document
---

# Introduction to problem/question
  
# Problem / Question
Crime, as what it always appears to be, is the negative power in our society that tends to trigger multiple problems. With the increasing demand for higher quality of life in the modern world, the general public attaches more attention to the safety of the living environment as one of the basic factors considered. There has been considerable effort extended to exploring and understanding the pattern of various types of crimes. There exists a sub-field, namely, geographic profiling, which is the marginal subject of criminology and geography, looking into the crime events with both the theoretical basics from criminology and spatial methodologies from geography, with the ultimate goal of promoting suggestions for reducing crime rates and maintaining social safety.

# Inspiring Examples

## Example 1
[Analyzing the geography of crime](https://www.youtube.com/watch?v=CDPjnUaMMIE)
<br>

From this video, I found out that we could explore crime incidents in GIS from the geographic perspective. And there are multiple methods to handle the crime data.

## Example 2

[Exploring the Link between Crime and Socio-Economic Status in Ottawa and Saskatoon: A Small-Area Geographical Analysis](https://www.justice.gc.ca/eng/rp-pr/csj-sjc/crime/rr06_6/p2.html)
<br>

From this article, I became aware that there were some correlation between crimes and socio-economic attributes.

# Proposed data sources

1. Crime incidents

2. Census Block Groups (CBGs) 2010 of the City of Buffalo

3. Sociodemographic data

# Proposed methods

The major method to be utilized in this project is visualization. Firstly, we want to create static and dynamic plots to show the changing behaviors of crime incidents from 2010 to 2020. Secondly, we will create an interactive map that depicts the spatial distribution of the crime incidents in Buffalo, NY. Finally, we also want to reveal the probable relationship between crime incidents and sociodemographic attributes.

# Expected results

1. Some plots showing the distribution in time and space of crime incidents in Buffalo.

2. The correlation between crime incidents and sociodemographic attributes.
