---
title: "Case Study 05: Beware the Canadians!"
author: "Wei Liu"
date: October 3, 2021
output: github_document
---

## Activate the packages that we need

```{r, message=FALSE}
library(spData)
library(sf)
library(tidyverse)
library(units)
```

## Load the data and explore a bit

dataset of world

```{r}
data(world)
st_crs(world)
```

dataset of us_states

```{r}
data(us_states)
st_crs(us_states)
```

## Prepare the data for buffering

Filter the world and us_states dataset to keep only "Canada" and "New York" respectively.

```{r}
Canada = filter(world, name_long=="Canada")
NY = filter(us_states, NAME=="New York")
```

Transform to the albers equal area projection defined below as albers.

```{r}
albers="+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
Canada_trans = st_transform(Canada, crs=albers)
NY_trans = st_transform(NY, crs=albers)
```

## Buffer, intersection and area

```{r}
Canada_buffer = st_buffer(Canada_trans, dist=10000) # The default unit is meter.
border = st_intersection(Canada_buffer, NY_trans)
st_area(border) %>% set_units(km^2)
```

## Plot out the border area
```{r, fig.align='center'}
ggplot() +
  geom_sf(data=NY_trans, fill="grey85") +
  geom_sf(data=border, fill="red") +
  labs(title="New York Land within 10km") +
  theme(plot.title = element_text(size=20L, hjust=0.5),
        axis.text = element_text(size=14L))
```